# Generated by Django 2.1.5 on 2020-03-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='year',
            new_name='year_stop',
        ),
        migrations.AddField(
            model_name='education',
            name='year_start',
            field=models.IntegerField(choices=[('1999', '1999'), ('2004', '2004')], default='1999'),
        ),
    ]
