# Generated by Django 2.1.5 on 2020-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_education_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='year_start',
        ),
        migrations.RemoveField(
            model_name='education',
            name='year_stop',
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='stop_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
