# Generated by Django 2.2.10 on 2020-03-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLanguageSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('RO', 'Romanian'), ('EN', 'English'), ('ES', 'Spanish')], max_length=10)),
            ],
            options={
                'verbose_name': 'My Language Skills',
                'verbose_name_plural': 'My Languages Skills',
            },
        ),
    ]
