# Generated by Django 2.2.10 on 2020-03-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_mylanguageskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylanguageskills',
            name='description',
        ),
    ]
