# Generated by Django 2.2.10 on 2020-03-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_remove_mylanguageskills_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylanguageskills',
            name='language',
            field=models.CharField(choices=[('Romanian', 'RO'), ('English', 'EN'), ('Spanish', 'ES')], max_length=10),
        ),
    ]
