# Generated by Django 2.2.10 on 2020-03-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20200321_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylanguageskills',
            name='language',
            field=models.CharField(choices=[('Romanian', 'Romanian'), ('English', 'English'), ('Spanish', 'Spanish')], max_length=10),
        ),
    ]
