# Generated by Django 2.2.10 on 2020-03-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20200321_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
