# Generated by Django 2.2.10 on 2020-03-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_experience_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTechnicalSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programing_language', models.CharField(choices=[('HMTL', 'HTML'), ('CSS', 'CSS'), ('JavaScript/jQuery', 'JS/jQ'), ('Ajax', 'Ajax'), ('Python', 'Python'), ('Django', 'Django'), ('Php', 'Php')], max_length=20)),
            ],
        ),
    ]
