# Generated by Django 2.2.10 on 2020-03-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_mytechnicalskills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytechnicalskills',
            options={'verbose_name': 'My Technical Skills', 'verbose_name_plural': 'My Technical Skills'},
        ),
        migrations.AlterField(
            model_name='mytechnicalskills',
            name='programing_language',
            field=models.CharField(choices=[('HMTL', 'HTML'), ('CSS', 'CSS'), ('JavaScript/jQuery', 'JavaScript/jQuery'), ('Ajax', 'Ajax'), ('Python', 'Python'), ('Django', 'Django'), ('Php', 'Php')], max_length=20),
        ),
    ]
