# Generated by Django 2.2.10 on 2020-03-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20200322_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytechnicalskills',
            name='programing_language',
            field=models.CharField(choices=[('HMTL', 'HTML'), ('CSS', 'CSS'), ('JavaScript/jQuery', 'JavaScript/jQuery'), ('Ajax', 'Ajax'), ('Python/Django', 'Python/Django'), ('Php/CodeIgniter', 'Php/CodeIgniter')], max_length=20),
        ),
    ]
