# Generated by Django 2.2.10 on 2020-03-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myportfolio',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
