# Generated by Django 2.2.10 on 2020-03-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_myportfolio_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myportfolio',
            old_name='categories',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='myportfolio',
            name='thumbnail',
        ),
    ]
