# Generated by Django 2.2.10 on 2020-05-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_auto_20200323_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myportfolio',
            name='items',
            field=models.CharField(choices=[('Python/Django', 'Python/Django'), ('HTML/CSS', 'HTML/CSS'), ('Joomla', 'Joomla'), ('Wordpress', 'Wordpress'), ('Python/PyQt5', 'Python/PyQt')], max_length=10),
        ),
    ]
